# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-16 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='business',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Neighbourhood',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
