# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-16 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0003_auto_20190916_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='photo',
        ),
    ]
