# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0005_auto_20190916_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='content',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
