# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-16 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='neighbourhood',
            new_name='project',
        ),
    ]
