# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-16 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0008_auto_20190916_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='project',
            new_name='neighbourhood',
        ),
    ]
